// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzdxk8xXC1mog8nx2LSl-9FRbRCu7dhzo',
    appId: '1:132449855961:web:59d8f514b47bbb371711c8',
    messagingSenderId: '132449855961',
    projectId: 'crypto-list-array',
    authDomain: 'crypto-list-array.firebaseapp.com',
    storageBucket: 'crypto-list-array.appspot.com',
    measurementId: 'G-GB2Y8T227K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3ovCMshB5_jJkjlkRQr7oTrw5VxMyYqE',
    appId: '1:132449855961:android:0185d7fdc0a096a11711c8',
    messagingSenderId: '132449855961',
    projectId: 'crypto-list-array',
    storageBucket: 'crypto-list-array.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTeTzQIMh-S2OOrOrZyRtdIJve0-esBug',
    appId: '1:132449855961:ios:c579142ebd2cbf741711c8',
    messagingSenderId: '132449855961',
    projectId: 'crypto-list-array',
    storageBucket: 'crypto-list-array.appspot.com',
    iosClientId: '132449855961-n1qa9a4rhd5aiifs50bv35bcud45ikmv.apps.googleusercontent.com',
    iosBundleId: 'com.cryptomorgtest.cryptoCoinsArray',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTeTzQIMh-S2OOrOrZyRtdIJve0-esBug',
    appId: '1:132449855961:ios:e8d66ae81f925dc61711c8',
    messagingSenderId: '132449855961',
    projectId: 'crypto-list-array',
    storageBucket: 'crypto-list-array.appspot.com',
    iosClientId: '132449855961-djp3tqsgfahsdugt8v1nip06ub9jh1mk.apps.googleusercontent.com',
    iosBundleId: 'com.cryptomorg.cryptoCoinsArray',
  );
}
